import { Organization, ConfounderAdjustment } from './enterpriseTypes';

export const GLOBAL_CONFOUNDER_RULES: ConfounderAdjustment[] = [
  {
    factor: 'Hair Wash Frequency (Daily Shampooing)',
    category: 'hygiene',
    description: 'Frequent surfactant contact extracts superficial cortisol from the hair cuticle.',
    rawImpactPercent: -18,
    normalizedFormula: 'Raw Pg/Mg × 1.22 (wash leaching recovery coefficient)',
    iconName: 'Droplets',
  },
  {
    factor: 'Chemical Bleaching & Dyes',
    category: 'chemical',
    description: 'Alkaline ammonia and peroxides partially degrade steroid hormone side-chains.',
    rawImpactPercent: -25,
    normalizedFormula: 'Raw Pg/Mg × 1.33 (keratin integrity offset)',
    iconName: 'Sparkles',
  },
  {
    factor: 'Ethnic Growth Velocity Standard',
    category: 'demographic',
    description: 'African (0.85 cm/mo), Asian (1.25 cm/mo), and Caucasian (1.05 cm/mo) growth rate calibration.',
    rawImpactPercent: 12,
    normalizedFormula: 'Segment Length × (1.0 / GrowthRate_cm)',
    iconName: 'Users',
  },
  {
    factor: 'Exogenous Corticosteroids & OCPs',
    category: 'pharmacology',
    description: 'Topical/inhaled steroids suppress endogenous cortisol; estrogen elevates CBG binding.',
    rawImpactPercent: 30,
    normalizedFormula: 'Free Cortisol Ratio = Total Cortisol / (CBG_Index × 0.85)',
    iconName: 'Pill',
  },
];

export const MOCK_ORGANIZATIONS: Record<string, Organization> = {
  'apollo-health': {
    id: 'apollo-health',
    name: 'Apollo Medical Center & AIIMS Network',
    sector: 'healthcare',
    subdomain: 'apollo-clinical',
    allowedDomains: ['aiims.edu', 'apollo.org', 'apollohospitals.com', 'health.gov.in'],
    logoEmoji: '🏥',
    location: 'New Delhi & Bengaluru Campus',
    totalMembers: 420,
    totalSampled: 388,
    currentCycle: {
      id: 'cycle-med-q3',
      name: 'Q3 2026 High-Acuity Surgical & Critical Rotation',
      period: 'Jul 1 – Sep 25, 2026',
      status: 'active',
      samplesCollected: 388,
      complianceRatePercent: 92.4,
      cliaLabCertified: true,
    },
    confounderProfiles: GLOBAL_CONFOUNDER_RULES,
    cohorts: [
      {
        id: 'em-dept',
        name: 'Emergency Medicine',
        code: 'EM-01',
        headOfficial: 'Dr. Vikram Malhotra (Clinical Chief of Emergency)',
        averageBsi: 82,
        overallRisk: 'critical',
        subUnits: [
          {
            id: 'em-day',
            name: 'Day Triage Squad',
            code: 'EM-D',
            memberCount: 28,
            sampledCount: 26,
            rawCortisolPgMg: 19.8,
            normalizedBsi: 64,
            riskLevel: 'elevated',
            previousQuarterBsi: 61,
            confoundersDetected: ['Hair Wash Daily (Surgical Scrub)', 'Caffeine Intake'],
            primaryStressDriver: 'Continuous Level-1 Trauma Admissions',
          },
          {
            id: 'em-night',
            name: 'Night Resuscitation Unit',
            code: 'EM-N',
            memberCount: 24,
            sampledCount: 24,
            rawCortisolPgMg: 28.4,
            normalizedBsi: 89,
            riskLevel: 'critical',
            previousQuarterBsi: 76,
            confoundersDetected: ['Hair Wash Daily', 'Circadian Phase Inversion'],
            primaryStressDriver: 'Rotational 14-Hour Night Shifts & Sleep Inversion',
          },
          {
            id: 'em-weekend',
            name: 'Weekend Surge Team',
            code: 'EM-W',
            memberCount: 18,
            sampledCount: 16,
            rawCortisolPgMg: 23.1,
            normalizedBsi: 74,
            riskLevel: 'elevated',
            previousQuarterBsi: 70,
            confoundersDetected: ['High Energy Drink Consumption'],
            primaryStressDriver: 'Multi-Victim Collision Surges',
          },
        ],
      },
      {
        id: 'icu-dept',
        name: 'Intensive Care Unit (ICU)',
        code: 'ICU-02',
        headOfficial: 'Dr. Sunita Varma (Director of Critical Care)',
        averageBsi: 78,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'icu-micu',
            name: 'Medical ICU (MICU)',
            code: 'ICU-M',
            memberCount: 32,
            sampledCount: 30,
            rawCortisolPgMg: 22.4,
            normalizedBsi: 72,
            riskLevel: 'elevated',
            previousQuarterBsi: 68,
            confoundersDetected: ['Surgical Caps 12h/day', 'High Daily Wash'],
            primaryStressDriver: 'Prolonged ARDS Ventilator Rounds',
          },
          {
            id: 'icu-sicu',
            name: 'Surgical ICU (SICU)',
            code: 'ICU-S',
            memberCount: 26,
            sampledCount: 25,
            rawCortisolPgMg: 26.8,
            normalizedBsi: 85,
            riskLevel: 'critical',
            previousQuarterBsi: 79,
            confoundersDetected: ['Surgical Caps', 'Post-Op Emergency Callouts'],
            primaryStressDriver: 'Acute Post-Transplant Rejection Monitoring',
          },
          {
            id: 'icu-nicu',
            name: 'Neonatal & Peds ICU',
            code: 'ICU-N',
            memberCount: 22,
            sampledCount: 20,
            rawCortisolPgMg: 18.2,
            normalizedBsi: 59,
            riskLevel: 'moderate',
            previousQuarterBsi: 56,
            confoundersDetected: ['Pediatric Ward Sanitization'],
            primaryStressDriver: 'High Emotional Compassion Fatigue',
          },
        ],
      },
      {
        id: 'surgery-dept',
        name: 'General & Trauma Surgery',
        code: 'SURG-03',
        headOfficial: 'Prof. Rajesh K. Nair (Head of Surgery)',
        averageBsi: 75,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'surg-resident',
            name: 'Junior Surgical Residents',
            code: 'SURG-RES',
            memberCount: 35,
            sampledCount: 34,
            rawCortisolPgMg: 27.2,
            normalizedBsi: 87,
            riskLevel: 'critical',
            previousQuarterBsi: 82,
            confoundersDetected: ['Daily Antiseptic Hair Rinse', 'Chronic Sleep Debt'],
            primaryStressDriver: '36-Hour Continuous On-Call Operating Blocks',
          },
          {
            id: 'surg-attending',
            name: 'Attending Staff Surgeons',
            code: 'SURG-ATT',
            memberCount: 20,
            sampledCount: 18,
            rawCortisolPgMg: 17.5,
            normalizedBsi: 56,
            riskLevel: 'moderate',
            previousQuarterBsi: 58,
            confoundersDetected: ['Controlled Duty Schedule'],
            primaryStressDriver: 'Complex Medico-Legal Operations',
          },
        ],
      },
      {
        id: 'peds-dept',
        name: 'Pediatrics & Neonatology',
        code: 'PEDS-04',
        headOfficial: 'Dr. Ananya Sen (Chair of Pediatrics)',
        averageBsi: 44,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'peds-outpatient',
            name: 'Outpatient Clinic',
            code: 'PEDS-OPD',
            memberCount: 25,
            sampledCount: 24,
            rawCortisolPgMg: 11.2,
            normalizedBsi: 34,
            riskLevel: 'nominal',
            previousQuarterBsi: 35,
            confoundersDetected: ['Standard Daytime Shifts'],
            primaryStressDriver: 'Routine Vaccinations & Well-Child Checks',
          },
          {
            id: 'peds-ward',
            name: 'Inpatient General Ward',
            code: 'PEDS-INP',
            memberCount: 22,
            sampledCount: 20,
            rawCortisolPgMg: 15.6,
            normalizedBsi: 48,
            riskLevel: 'moderate',
            previousQuarterBsi: 46,
            confoundersDetected: ['Mild Sleep Interruptions'],
            primaryStressDriver: 'Night Admissions & Dehydration Cases',
          },
        ],
      },
      {
        id: 'oncol-dept',
        name: 'Medical Oncology & Palliative',
        code: 'ONC-05',
        headOfficial: 'Dr. Siddharth Rao (Director of Oncology)',
        averageBsi: 54,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'onc-chemo',
            name: 'Chemo Infusion Daycare',
            code: 'ONC-CHM',
            memberCount: 19,
            sampledCount: 18,
            rawCortisolPgMg: 14.8,
            normalizedBsi: 47,
            riskLevel: 'moderate',
            previousQuarterBsi: 50,
            confoundersDetected: ['Sterile Prep Protocols'],
            primaryStressDriver: 'Strict Infusion Timing Protocols',
          },
          {
            id: 'onc-palliative',
            name: 'Palliative Care & Hospice',
            code: 'ONC-PAL',
            memberCount: 16,
            sampledCount: 15,
            rawCortisolPgMg: 17.9,
            normalizedBsi: 61,
            riskLevel: 'elevated',
            previousQuarterBsi: 58,
            confoundersDetected: ['High Emotional Empathy Load'],
            primaryStressDriver: 'End-of-Life Family Counseling',
          },
        ],
      },
    ],
    interventions: [
      {
        id: 'int-em-01',
        title: 'Mandatory Post-Night-Call Digital Pager Curfew',
        targetCohortId: 'em-dept',
        targetUnitId: 'em-night',
        targetUnitName: 'Night Resuscitation Unit',
        category: 'circadian_curfew',
        rationale: 'Post-call physicians receiving non-urgent administrative pages experience immediate REM-sleep fragmentation.',
        projectedBsiReductionPercent: 26,
        actionProtocol: 'Automated 8:00 AM – 3:00 PM paging blackout with mandatory handover to daytime hospitalists.',
        status: 'recommended',
        timeToImpactDays: 21,
      },
      {
        id: 'int-surg-02',
        title: '36-Hour Shift Cap & Mandatory Circadian Micro-Sleep Pods',
        targetCohortId: 'surgery-dept',
        targetUnitId: 'surg-resident',
        targetUnitName: 'Junior Surgical Residents',
        category: 'roster_pacing',
        rationale: 'Continuous operative duty beyond 24 hours induces a 3.4x spike in chronic follicular cortisol deposition.',
        projectedBsiReductionPercent: 32,
        actionProtocol: 'Split 36h calls into 14h day / 10h rest / 12h twilight rotations with dedicated quiet dark-rooms.',
        status: 'recommended',
        timeToImpactDays: 30,
      },
      {
        id: 'int-icu-03',
        title: 'Dynamic Autonomic Reset Breaks Post-Code Blue',
        targetCohortId: 'icu-dept',
        targetUnitId: 'icu-sicu',
        targetUnitName: 'Surgical ICU (SICU)',
        category: 'workload_cap',
        rationale: 'Acute sympathetic overdrive after cardiac arrest resuscitations fails to down-regulate without structured pacing.',
        projectedBsiReductionPercent: 18,
        actionProtocol: 'Mandatory 20-minute vagal stimulation / breathwork break immediately following active resuscitation.',
        status: 'recommended',
        timeToImpactDays: 14,
      },
    ],
  },

  'st-jude-academy': {
    id: 'st-jude-academy',
    name: 'St. Jude International Academy & High School',
    sector: 'education',
    subdomain: 'stjude-students',
    allowedDomains: ['stjude.edu', 'stjude.org', 'k12.in', 'schools.org'],
    logoEmoji: '🎓',
    location: 'Bangalore & Hyderabad Campus',
    totalMembers: 680,
    totalSampled: 642,
    currentCycle: {
      id: 'cycle-edu-term1',
      name: 'Term 1 Pre-Board & Competitive Exam Cycle',
      period: 'Aug 1 – Sep 20, 2026',
      status: 'active',
      samplesCollected: 642,
      complianceRatePercent: 94.4,
      cliaLabCertified: true,
    },
    confounderProfiles: GLOBAL_CONFOUNDER_RULES,
    cohorts: [
      {
        id: 'gr-9',
        name: 'Grade 9 (Freshmen)',
        code: 'GR-09',
        headOfficial: 'Meera Chawla (Head of Middle School Transition)',
        averageBsi: 38,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'gr9-a',
            name: 'Section 9-A',
            code: '9-A',
            memberCount: 38,
            sampledCount: 36,
            rawCortisolPgMg: 11.5,
            normalizedBsi: 36,
            riskLevel: 'moderate',
            previousQuarterBsi: 32,
            confoundersDetected: ['Pediatric Growth Curve Normalization'],
            primaryStressDriver: 'High School Curriculum Transition',
          },
          {
            id: 'gr9-b',
            name: 'Section 9-B',
            code: '9-B',
            memberCount: 40,
            sampledCount: 38,
            rawCortisolPgMg: 12.1,
            normalizedBsi: 39,
            riskLevel: 'moderate',
            previousQuarterBsi: 34,
            confoundersDetected: ['Pediatric Growth Curve Normalization'],
            primaryStressDriver: 'Sports & Co-Curricular Scheduling',
          },
        ],
      },
      {
        id: 'gr-10',
        name: 'Grade 10 (Foundations)',
        code: 'GR-10',
        headOfficial: 'Robert Hughes (Academic Dean)',
        averageBsi: 52,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'gr10-a',
            name: 'Section 10-A (STEM Focus)',
            code: '10-A',
            memberCount: 42,
            sampledCount: 40,
            rawCortisolPgMg: 16.4,
            normalizedBsi: 56,
            riskLevel: 'moderate',
            previousQuarterBsi: 48,
            confoundersDetected: ['Daily Hair Wash'],
            primaryStressDriver: 'Early Foundation Tests for JEE/NEET',
          },
          {
            id: 'gr10-b',
            name: 'Section 10-B (Liberal Arts)',
            code: '10-B',
            memberCount: 36,
            sampledCount: 34,
            rawCortisolPgMg: 13.9,
            normalizedBsi: 46,
            riskLevel: 'moderate',
            previousQuarterBsi: 44,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Term Paper Submissions',
          },
        ],
      },
      {
        id: 'gr-11',
        name: 'Grade 11 (Competitive AP / JEE Cohort)',
        code: 'GR-11',
        headOfficial: 'Dr. K. S. Pillai (Director of Advanced Placements)',
        averageBsi: 84,
        overallRisk: 'critical',
        subUnits: [
          {
            id: 'gr11-stem',
            name: 'Section 11-A (Engineering / Math)',
            code: '11-A',
            memberCount: 44,
            sampledCount: 43,
            rawCortisolPgMg: 26.5,
            normalizedBsi: 86,
            riskLevel: 'critical',
            previousQuarterBsi: 72,
            confoundersDetected: ['Late Night Screentime', 'Adolescent Melatonin Shift'],
            primaryStressDriver: 'Simultaneous Weekend Coaching & School Mock Tests',
          },
          {
            id: 'gr11-med',
            name: 'Section 11-B (Biomedical & Pre-Med)',
            code: '11-B',
            memberCount: 41,
            sampledCount: 40,
            rawCortisolPgMg: 27.9,
            normalizedBsi: 89,
            riskLevel: 'critical',
            previousQuarterBsi: 74,
            confoundersDetected: ['Chronic Sleep Debt (<5.5h)', 'Daily Hair Wash'],
            primaryStressDriver: 'Daily Cumulative 14-Hour Study Days + Late Night Portals',
          },
          {
            id: 'gr11-com',
            name: 'Section 11-C (Commerce & Economics)',
            code: '11-C',
            memberCount: 38,
            sampledCount: 36,
            rawCortisolPgMg: 18.2,
            normalizedBsi: 62,
            riskLevel: 'elevated',
            previousQuarterBsi: 55,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Accountancy Practicals & Presentations',
          },
        ],
      },
      {
        id: 'gr-12',
        name: 'Grade 12 (Board Finals & College Applications)',
        code: 'GR-12',
        headOfficial: 'Patricia Lewis (College Counseling Lead)',
        averageBsi: 79,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'gr12-stem',
            name: 'Section 12-A (Advanced STEM)',
            code: '12-A',
            memberCount: 45,
            sampledCount: 44,
            rawCortisolPgMg: 25.1,
            normalizedBsi: 82,
            riskLevel: 'critical',
            previousQuarterBsi: 77,
            confoundersDetected: ['Sleep Fragmentation', 'Caffeine Spikes'],
            primaryStressDriver: 'College Early Decision Deadlines + Pre-Board Finals',
          },
          {
            id: 'gr12-arts',
            name: 'Section 12-B (Humanities & Law)',
            code: '12-B',
            memberCount: 35,
            sampledCount: 33,
            rawCortisolPgMg: 21.0,
            normalizedBsi: 68,
            riskLevel: 'elevated',
            previousQuarterBsi: 63,
            confoundersDetected: ['Standard Wash Habits'],
            primaryStressDriver: 'Portfolio Submissions & Entrance Mocks',
          },
        ],
      },
    ],
    interventions: [
      {
        id: 'int-edu-01',
        title: 'Institutional Homework Portal Curfew (10:00 PM – 6:00 AM)',
        targetCohortId: 'gr-11',
        targetUnitId: 'gr11-med',
        targetUnitName: 'Section 11-B (Biomedical & Pre-Med)',
        category: 'circadian_curfew',
        rationale: 'Late-night digital homework submissions directly suppress adolescent slow-wave sleep and cause biological morning exhaustion.',
        projectedBsiReductionPercent: 28,
        actionProtocol: 'Automatic portal upload lock between 10 PM and 6 AM. Late penalties waived for work submitted after 6 AM.',
        status: 'recommended',
        timeToImpactDays: 14,
      },
      {
        id: 'int-edu-02',
        title: '72-Hour Exam Spacing Mandate for High-Stakes Tests',
        targetCohortId: 'gr-11',
        targetUnitId: 'gr11-stem',
        targetUnitName: 'Section 11-A (Engineering / Math)',
        category: 'roster_pacing',
        rationale: 'Back-to-back testing days prevent HPA-axis down-regulation, causing continuous elevated cortisol wash.',
        projectedBsiReductionPercent: 22,
        actionProtocol: 'No two major subject tests allowed within 72 hours of each other across departments.',
        status: 'recommended',
        timeToImpactDays: 20,
      },
      {
        id: 'int-edu-03',
        title: 'Adolescent Melatonin Delay Alignment (8:45 AM Start)',
        targetCohortId: 'gr-12',
        targetUnitId: 'gr12-stem',
        targetUnitName: 'Section 12-A (Advanced STEM)',
        category: 'environmental',
        rationale: 'Adolescents have a biologically delayed melatonin phase of ~1.5 hours compared to adults.',
        projectedBsiReductionPercent: 19,
        actionProtocol: 'Shift first period from 7:45 AM to 8:45 AM for Grade 11 & 12 students.',
        status: 'recommended',
        timeToImpactDays: 30,
      },
    ],
  },

  'nexus-tech': {
    id: 'nexus-tech',
    name: 'Nexus Technologies & Stripe Global',
    sector: 'corporate',
    subdomain: 'nexus-enterprise',
    allowedDomains: ['stripe.com', 'nexustech.io', 'google.com', 'meta.com'],
    logoEmoji: '🏢',
    location: 'San Francisco & Bangalore Hubs',
    totalMembers: 520,
    totalSampled: 490,
    currentCycle: {
      id: 'cycle-corp-q3',
      name: 'Q3 Enterprise Scale & Production Delivery Cycle',
      period: 'Jul 1 – Sep 20, 2026',
      status: 'active',
      samplesCollected: 490,
      complianceRatePercent: 94.2,
      cliaLabCertified: true,
    },
    confounderProfiles: GLOBAL_CONFOUNDER_RULES,
    cohorts: [
      {
        id: 'infra-eng',
        name: 'Core Infrastructure & Reliability',
        code: 'ENG-INFRA',
        headOfficial: 'Elena Vance (VP of Infrastructure)',
        averageBsi: 76,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'infra-oncall',
            name: 'Tier-1 Reliability On-Call Squad',
            code: 'INFRA-P1',
            memberCount: 28,
            sampledCount: 27,
            rawCortisolPgMg: 26.1,
            normalizedBsi: 84,
            riskLevel: 'critical',
            previousQuarterBsi: 74,
            confoundersDetected: ['Midnight Pager Duty', 'Daily Wash'],
            primaryStressDriver: 'Midnight Production Incidents & 5-Minute SLA Pagers',
          },
          {
            id: 'infra-cloud',
            name: 'Cloud Architecture & FinOps',
            code: 'INFRA-CLD',
            memberCount: 32,
            sampledCount: 30,
            rawCortisolPgMg: 19.5,
            normalizedBsi: 62,
            riskLevel: 'elevated',
            previousQuarterBsi: 60,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Cross-Timezone Datacenter Migrations',
          },
        ],
      },
      {
        id: 'ent-sales',
        name: 'Global Enterprise Sales',
        code: 'SALES-ENT',
        headOfficial: 'Marcus Sterling (Chief Revenue Officer)',
        averageBsi: 83,
        overallRisk: 'critical',
        subUnits: [
          {
            id: 'sales-americas',
            name: 'Americas Enterprise Team',
            code: 'SALES-US',
            memberCount: 36,
            sampledCount: 35,
            rawCortisolPgMg: 28.5,
            normalizedBsi: 89,
            riskLevel: 'critical',
            previousQuarterBsi: 75,
            confoundersDetected: ['Red-Eye Flight Travel (Timezone Shift)', 'Coffee Surge'],
            primaryStressDriver: 'Quarter-End Quota Pressures & Cross-Country Red-Eye Flights',
          },
          {
            id: 'sales-apac',
            name: 'APAC & EMEA Expansion',
            code: 'SALES-INTL',
            memberCount: 30,
            sampledCount: 28,
            rawCortisolPgMg: 24.3,
            normalizedBsi: 78,
            riskLevel: 'elevated',
            previousQuarterBsi: 72,
            confoundersDetected: ['Late Night US Bridge Calls'],
            primaryStressDriver: '10 PM - 2 AM HQ Alignment Video Calls',
          },
        ],
      },
      {
        id: 'prod-ux',
        name: 'Product & User Experience',
        code: 'PROD-UX',
        headOfficial: 'Sarah Lin (Chief Product Officer)',
        averageBsi: 48,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'prod-core',
            name: 'Core Application Squad',
            code: 'PROD-APP',
            memberCount: 34,
            sampledCount: 32,
            rawCortisolPgMg: 15.2,
            normalizedBsi: 48,
            riskLevel: 'moderate',
            previousQuarterBsi: 46,
            confoundersDetected: ['Regular Flexible Hours'],
            primaryStressDriver: 'Feature Launch Deadlines',
          },
          {
            id: 'prod-research',
            name: 'User Research & Insights',
            code: 'PROD-RES',
            memberCount: 20,
            sampledCount: 19,
            rawCortisolPgMg: 12.0,
            normalizedBsi: 35,
            riskLevel: 'nominal',
            previousQuarterBsi: 38,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Qualitative Field Testing',
          },
        ],
      },
      {
        id: 'cust-ops',
        name: 'Customer Success & Tier-3 Support',
        code: 'CS-OPS',
        headOfficial: 'Tariq Al-Mansoor (VP of Customer Success)',
        averageBsi: 65,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'cs-escalation',
            name: 'VIP Escalation Cell',
            code: 'CS-VIP',
            memberCount: 26,
            sampledCount: 25,
            rawCortisolPgMg: 22.8,
            normalizedBsi: 73,
            riskLevel: 'elevated',
            previousQuarterBsi: 69,
            confoundersDetected: ['Continuous High Tone Stress'],
            primaryStressDriver: 'High-Value Client Churn Threat Escalations',
          },
          {
            id: 'cs-onboarding',
            name: 'Implementation & Integrations',
            code: 'CS-INT',
            memberCount: 25,
            sampledCount: 24,
            rawCortisolPgMg: 17.1,
            normalizedBsi: 52,
            riskLevel: 'moderate',
            previousQuarterBsi: 50,
            confoundersDetected: ['Standard Daytime Shifts'],
            primaryStressDriver: 'ERP Data Migration Cutover Deadlines',
          },
        ],
      },
    ],
    interventions: [
      {
        id: 'int-corp-01',
        title: 'Asynchronous Focus Days (No-Meeting Thursdays)',
        targetCohortId: 'infra-eng',
        targetUnitId: 'infra-oncall',
        targetUnitName: 'Tier-1 Reliability On-Call Squad',
        category: 'workload_cap',
        rationale: 'Back-to-back contextual switching combined with on-call alerts induces permanent sympathetic hyper-arousal.',
        projectedBsiReductionPercent: 24,
        actionProtocol: 'Total calendar lock for internal meetings every Thursday; asynchronous Slack updates only.',
        status: 'recommended',
        timeToImpactDays: 14,
      },
      {
        id: 'int-corp-02',
        title: 'Post-Quarter 72-Hour Biological Recovery Window',
        targetCohortId: 'ent-sales',
        targetUnitId: 'sales-americas',
        targetUnitName: 'Americas Enterprise Team',
        category: 'roster_pacing',
        rationale: 'The end-of-quarter push produces a 38% spike in follicular cortisol that persists for 30+ days without recovery buffers.',
        projectedBsiReductionPercent: 30,
        actionProtocol: 'Mandatory 3-day quiet sprint with zero internal reviews or quota calls immediately following quarter close.',
        status: 'recommended',
        timeToImpactDays: 21,
      },
      {
        id: 'int-corp-03',
        title: 'Strict 7:00 PM Cross-Timezone Curfew Rule',
        targetCohortId: 'ent-sales',
        targetUnitId: 'sales-apac',
        targetUnitName: 'APAC & EMEA Expansion',
        category: 'circadian_curfew',
        rationale: 'Attending California meetings at 11 PM IST disrupts nocturnal cortisol nadir, causing chronic sleep degradation.',
        projectedBsiReductionPercent: 25,
        actionProtocol: 'No meetings scheduled outside 8 AM – 7 PM local time for all international regional teams.',
        status: 'recommended',
        timeToImpactDays: 14,
      },
    ],
  },
};
