import { Organization, ConfounderAdjustment } from './enterpriseTypes';

export const GLOBAL_CONFOUNDER_RULES: ConfounderAdjustment[] = [
  {
    factor: 'Hair Wash Frequency (Daily Shampooing)',
    category: 'hygiene',
    description: 'Frequent surfactant contact extracts superficial cortisol from the hair cuticle.',
    rawImpactPercent: -18,
    normalizedFormula: 'Raw Pg/Mg × 1.22 (wash leaching recovery coefficient)',
    iconName: 'Droplets',
  },
  {
    factor: 'Chemical Bleaching & Dyes',
    category: 'chemical',
    description: 'Alkaline ammonia and peroxides partially degrade steroid hormone side-chains.',
    rawImpactPercent: -25,
    normalizedFormula: 'Raw Pg/Mg × 1.33 (keratin integrity offset)',
    iconName: 'Sparkles',
  },
  {
    factor: 'Ethnic Growth Velocity Standard',
    category: 'demographic',
    description: 'African (0.85 cm/mo), Asian (1.25 cm/mo), and Caucasian (1.05 cm/mo) growth rate calibration.',
    rawImpactPercent: 12,
    normalizedFormula: 'Segment Length × (1.0 / GrowthRate_cm)',
    iconName: 'Users',
  },
  {
    factor: 'Exogenous Corticosteroids & OCPs',
    category: 'pharmacology',
    description: 'Topical/inhaled steroids suppress endogenous cortisol; estrogen elevates CBG binding.',
    rawImpactPercent: 30,
    normalizedFormula: 'Free Cortisol Ratio = Total Cortisol / (CBG_Index × 0.85)',
    iconName: 'Pill',
  },
];

export const MOCK_ORGANIZATIONS: Record<string, Organization> = {
  'apollo-health': {
    id: 'apollo-health',
    name: 'Apollo Medical Center & AIIMS Network',
    sector: 'healthcare',
    subdomain: 'apollo-clinical',
    allowedDomains: ['aiims.edu', 'apollo.org', 'apollohospitals.com', 'health.gov.in'],
    logoEmoji: '🏥',
    location: 'New Delhi & Bengaluru Campus',
    totalMembers: 760,
    totalSampled: 712,
    currentCycle: {
      id: 'cycle-med-q3',
      name: 'Q3 2026 High-Acuity Surgical & Critical Rotation',
      period: 'Jul 1 – Sep 28, 2026',
      status: 'active',
      samplesCollected: 712,
      complianceRatePercent: 93.6,
      cliaLabCertified: true,
    },
    cohorts: [
      {
        id: 'em-dept',
        name: 'Emergency Medicine',
        code: 'EM-01',
        iconKey: 'emergency',
        headOfficial: 'Dr. Vikram Malhotra (Chief of Emergency)',
        averageBurnoutScore: 82,
        averageBsi: 82,
        overallRisk: 'critical',
        subUnits: [
          {
            id: 'em-day',
            name: 'Day Triage Squad',
            code: 'EM-D',
            iconKey: 'day',
            memberCount: 28,
            sampledCount: 26,
            rawCortisolPgMg: 19.8,
            burnoutScore: 64,
            normalizedBsi: 64,
            riskLevel: 'elevated',
            previousQuarterScore: 61,
            previousQuarterBsi: 61,
            confoundersDetected: ['Surgical Scrub Shampoo Daily'],
            primaryStressDriver: 'Continuous Level-1 Trauma Admissions',
          },
          {
            id: 'em-night',
            name: 'Night Resuscitation Unit',
            code: 'EM-N',
            iconKey: 'night',
            memberCount: 24,
            sampledCount: 24,
            rawCortisolPgMg: 28.4,
            burnoutScore: 89,
            normalizedBsi: 89,
            riskLevel: 'critical',
            previousQuarterScore: 76,
            previousQuarterBsi: 76,
            confoundersDetected: ['Inverted Circadian Phase', 'Daily Antiseptic Wash'],
            primaryStressDriver: 'Rotational 14-Hour Night Shifts & Resuscitation Waves',
          },
          {
            id: 'em-weekend',
            name: 'Weekend Trauma Surge Team',
            code: 'EM-W',
            iconKey: 'surge',
            memberCount: 20,
            sampledCount: 19,
            rawCortisolPgMg: 23.1,
            burnoutScore: 74,
            normalizedBsi: 74,
            riskLevel: 'elevated',
            previousQuarterScore: 70,
            previousQuarterBsi: 70,
            confoundersDetected: ['High Caffeine Spikes'],
            primaryStressDriver: 'Multi-Victim Collision Surges',
          },
        ],
      },
      {
        id: 'icu-dept',
        name: 'Intensive Care Unit (ICU)',
        code: 'ICU-02',
        iconKey: 'icu',
        headOfficial: 'Dr. Sunita Varma (Critical Care Director)',
        averageBurnoutScore: 78,
        averageBsi: 78,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'icu-micu',
            name: 'Medical ICU (MICU)',
            code: 'ICU-M',
            iconKey: 'micu',
            memberCount: 32,
            sampledCount: 30,
            rawCortisolPgMg: 22.4,
            burnoutScore: 72,
            normalizedBsi: 72,
            riskLevel: 'elevated',
            previousQuarterScore: 68,
            previousQuarterBsi: 68,
            confoundersDetected: ['Continuous Surgical Cap Pressure'],
            primaryStressDriver: 'Prolonged ARDS Ventilator Rounds',
          },
          {
            id: 'icu-sicu',
            name: 'Surgical ICU (SICU)',
            code: 'ICU-S',
            iconKey: 'sicu',
            memberCount: 26,
            sampledCount: 25,
            rawCortisolPgMg: 26.8,
            burnoutScore: 85,
            normalizedBsi: 85,
            riskLevel: 'critical',
            previousQuarterScore: 79,
            previousQuarterBsi: 79,
            confoundersDetected: ['Post-Op Emergency Callouts'],
            primaryStressDriver: 'Acute Post-Transplant Rejection Monitoring',
          },
          {
            id: 'icu-nicu',
            name: 'Neonatal & Peds ICU (NICU)',
            code: 'ICU-N',
            iconKey: 'nicu',
            memberCount: 22,
            sampledCount: 21,
            rawCortisolPgMg: 18.2,
            burnoutScore: 59,
            normalizedBsi: 59,
            riskLevel: 'moderate',
            previousQuarterScore: 56,
            previousQuarterBsi: 56,
            confoundersDetected: ['Standard Daytime Shifts'],
            primaryStressDriver: 'Emotional Compassion Fatigue in Preterm Care',
          },
        ],
      },
      {
        id: 'surgery-dept',
        name: 'General & Trauma Surgery',
        code: 'SURG-03',
        iconKey: 'surgery',
        headOfficial: 'Prof. Rajesh K. Nair (Head of Surgery)',
        averageBurnoutScore: 79,
        averageBsi: 79,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'surg-resident',
            name: 'Junior Surgical Residents',
            code: 'SURG-RES',
            iconKey: 'resident',
            memberCount: 35,
            sampledCount: 34,
            rawCortisolPgMg: 27.2,
            burnoutScore: 87,
            normalizedBsi: 87,
            riskLevel: 'critical',
            previousQuarterScore: 82,
            previousQuarterBsi: 82,
            confoundersDetected: ['36-Hour Continuous Operative Duty'],
            primaryStressDriver: 'Continuous On-Call Operative Blocks & Zero Sleep Windows',
          },
          {
            id: 'surg-attending',
            name: 'Attending Staff Surgeons',
            code: 'SURG-ATT',
            iconKey: 'attending',
            memberCount: 20,
            sampledCount: 18,
            rawCortisolPgMg: 17.5,
            burnoutScore: 56,
            normalizedBsi: 56,
            riskLevel: 'moderate',
            previousQuarterScore: 58,
            previousQuarterBsi: 58,
            confoundersDetected: ['Scheduled Elective Rotations'],
            primaryStressDriver: 'Complex Medico-Legal Operations',
          },
          {
            id: 'surg-trauma',
            name: 'Trauma Operating Bay',
            code: 'SURG-TRM',
            iconKey: 'surge',
            memberCount: 18,
            sampledCount: 17,
            rawCortisolPgMg: 24.6,
            burnoutScore: 80,
            normalizedBsi: 80,
            riskLevel: 'elevated',
            previousQuarterScore: 75,
            previousQuarterBsi: 75,
            confoundersDetected: ['Emergency Exploratory Laparotomies'],
            primaryStressDriver: 'Night-Time Damage Control Laparotomies',
          },
        ],
      },
      {
        id: 'cardio-dept',
        name: 'Cardiology & Cath Lab',
        code: 'CARD-04',
        iconKey: 'cardiology',
        headOfficial: 'Dr. Srinivas Reddy (Chief Cardiologist)',
        averageBurnoutScore: 73,
        averageBsi: 73,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'card-stemi',
            name: 'Acute STEMI 24/7 Response Team',
            code: 'CARD-STEMI',
            iconKey: 'oncall',
            memberCount: 22,
            sampledCount: 21,
            rawCortisolPgMg: 26.0,
            burnoutScore: 83,
            normalizedBsi: 83,
            riskLevel: 'critical',
            previousQuarterScore: 78,
            previousQuarterBsi: 78,
            confoundersDetected: ['90-Minute Door-to-Balloon Pagers'],
            primaryStressDriver: 'Rapid Midnight Primary Angioplasty Activations',
          },
          {
            id: 'card-ccu',
            name: 'Cardiac Critical Unit (CCU)',
            code: 'CARD-CCU',
            iconKey: 'micu',
            memberCount: 24,
            sampledCount: 22,
            rawCortisolPgMg: 20.4,
            burnoutScore: 68,
            normalizedBsi: 68,
            riskLevel: 'elevated',
            previousQuarterScore: 65,
            previousQuarterBsi: 65,
            confoundersDetected: ['Cardiogenic Shock Monitoring'],
            primaryStressDriver: 'Intra-Aortic Balloon Pump (IABP) Overwatches',
          },
          {
            id: 'card-opd',
            name: 'Outpatient Diagnostics & Echo',
            code: 'CARD-OPD',
            iconKey: 'day',
            memberCount: 18,
            sampledCount: 17,
            rawCortisolPgMg: 13.5,
            burnoutScore: 42,
            normalizedBsi: 42,
            riskLevel: 'moderate',
            previousQuarterScore: 40,
            previousQuarterBsi: 40,
            confoundersDetected: ['Standard Daytime Shifts'],
            primaryStressDriver: 'High-Volume Stress Echo Patient Backlog',
          },
        ],
      },
      {
        id: 'neuro-dept',
        name: 'Neurology & Stroke Center',
        code: 'NEURO-05',
        iconKey: 'neurology',
        headOfficial: 'Dr. Kavita Narang (Director of Neuroscience)',
        averageBurnoutScore: 75,
        averageBsi: 75,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'neuro-stroke',
            name: 'Acute Stroke Code Team',
            code: 'NEURO-STRK',
            iconKey: 'oncall',
            memberCount: 20,
            sampledCount: 19,
            rawCortisolPgMg: 25.4,
            burnoutScore: 82,
            normalizedBsi: 82,
            riskLevel: 'critical',
            previousQuarterScore: 77,
            previousQuarterBsi: 77,
            confoundersDetected: ['4.5-Hour Thrombolysis Window Pressure'],
            primaryStressDriver: 'Emergency Mechanical Thrombectomy Scrambles',
          },
          {
            id: 'neuro-icu',
            name: 'Neuro-ICU Unit',
            code: 'NEURO-ICU',
            iconKey: 'micu',
            memberCount: 22,
            sampledCount: 21,
            rawCortisolPgMg: 23.0,
            burnoutScore: 74,
            normalizedBsi: 74,
            riskLevel: 'elevated',
            previousQuarterScore: 71,
            previousQuarterBsi: 71,
            confoundersDetected: ['ICP Monitoring Vigilance'],
            primaryStressDriver: 'Intracranial Pressure Crisis Management',
          },
        ],
      },
      {
        id: 'anes-dept',
        name: 'Anesthesiology & Perioperative',
        code: 'ANES-06',
        iconKey: 'anesthesia',
        headOfficial: 'Dr. Harish K. Gupta (Chair of Anesthesia)',
        averageBurnoutScore: 71,
        averageBsi: 71,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'anes-ob',
            name: 'Obstetric Emergency Anesthesia',
            code: 'ANES-OB',
            iconKey: 'night',
            memberCount: 19,
            sampledCount: 18,
            rawCortisolPgMg: 24.8,
            burnoutScore: 78,
            normalizedBsi: 78,
            riskLevel: 'elevated',
            previousQuarterScore: 74,
            previousQuarterBsi: 74,
            confoundersDetected: ['Stat Cesarean Delivery Pagers'],
            primaryStressDriver: 'Emergency General Anesthesia for Fetal Distress',
          },
          {
            id: 'anes-or',
            name: 'Main Operating Suite Anesthesia',
            code: 'ANES-OR',
            iconKey: 'day',
            memberCount: 26,
            sampledCount: 25,
            rawCortisolPgMg: 19.8,
            burnoutScore: 65,
            normalizedBsi: 65,
            riskLevel: 'elevated',
            previousQuarterScore: 62,
            previousQuarterBsi: 62,
            confoundersDetected: ['Back-to-Back Intubations'],
            primaryStressDriver: 'Prolonged Organ Harvest & Transplant Anesthesia',
          },
        ],
      },
      {
        id: 'peds-dept',
        name: 'Pediatrics & Neonatology',
        code: 'PEDS-07',
        iconKey: 'pediatrics',
        headOfficial: 'Dr. Ananya Sen (Chair of Pediatrics)',
        averageBurnoutScore: 44,
        averageBsi: 44,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'peds-outpatient',
            name: 'Outpatient Clinic',
            code: 'PEDS-OPD',
            iconKey: 'day',
            memberCount: 25,
            sampledCount: 24,
            rawCortisolPgMg: 11.2,
            burnoutScore: 34,
            normalizedBsi: 34,
            riskLevel: 'nominal',
            previousQuarterScore: 35,
            previousQuarterBsi: 35,
            confoundersDetected: ['Standard Daytime Shifts'],
            primaryStressDriver: 'Routine Vaccinations & Well-Child Checks',
          },
          {
            id: 'peds-ward',
            name: 'Inpatient General Ward',
            code: 'PEDS-INP',
            iconKey: 'night',
            memberCount: 22,
            sampledCount: 20,
            rawCortisolPgMg: 15.6,
            burnoutScore: 48,
            normalizedBsi: 48,
            riskLevel: 'moderate',
            previousQuarterScore: 46,
            previousQuarterBsi: 46,
            confoundersDetected: ['Mild Sleep Interruptions'],
            primaryStressDriver: 'Pediatric Inpatient Fluid Balance Rounds',
          },
        ],
      },
      {
        id: 'oncol-dept',
        name: 'Medical Oncology & BMT',
        code: 'ONC-08',
        iconKey: 'oncology',
        headOfficial: 'Dr. Siddharth Rao (Director of Oncology)',
        averageBurnoutScore: 58,
        averageBsi: 58,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'onc-chemo',
            name: 'Chemo Infusion Daycare',
            code: 'ONC-CHM',
            iconKey: 'day',
            memberCount: 19,
            sampledCount: 18,
            rawCortisolPgMg: 14.8,
            burnoutScore: 47,
            normalizedBsi: 47,
            riskLevel: 'moderate',
            previousQuarterScore: 50,
            previousQuarterBsi: 50,
            confoundersDetected: ['Sterile Protocol Focus'],
            primaryStressDriver: 'High-Volume Chemotherapy Regimen Titration',
          },
          {
            id: 'onc-bmt',
            name: 'Bone Marrow Transplant (BMT) Unit',
            code: 'ONC-BMT',
            iconKey: 'surge',
            memberCount: 16,
            sampledCount: 15,
            rawCortisolPgMg: 23.9,
            burnoutScore: 76,
            normalizedBsi: 76,
            riskLevel: 'elevated',
            previousQuarterScore: 72,
            previousQuarterBsi: 72,
            confoundersDetected: ['Graft-vs-Host Crisis Vigilance'],
            primaryStressDriver: 'Neutropenic Fever Emergencies',
          },
        ],
      },
      {
        id: 'ortho-dept',
        name: 'Orthopedics & Spine Trauma',
        code: 'ORTHO-09',
        iconKey: 'orthopedics',
        headOfficial: 'Dr. Ajay Verma (Chief of Orthopedic Surgery)',
        averageBurnoutScore: 68,
        averageBsi: 68,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'ortho-trauma',
            name: 'Poly-Trauma Fracture Squad',
            code: 'ORTHO-TRM',
            iconKey: 'surge',
            memberCount: 22,
            sampledCount: 21,
            rawCortisolPgMg: 24.5,
            burnoutScore: 79,
            normalizedBsi: 79,
            riskLevel: 'elevated',
            previousQuarterScore: 73,
            previousQuarterBsi: 73,
            confoundersDetected: ['Heavy Physical Fluoroscopy Armor Strain'],
            primaryStressDriver: 'Immediate External Fixations for Pelvic Fractures',
          },
          {
            id: 'ortho-joint',
            name: 'Joint & Spine Reconstruction',
            code: 'ORTHO-REC',
            iconKey: 'attending',
            memberCount: 18,
            sampledCount: 17,
            rawCortisolPgMg: 16.9,
            burnoutScore: 53,
            normalizedBsi: 53,
            riskLevel: 'moderate',
            previousQuarterScore: 51,
            previousQuarterBsi: 51,
            confoundersDetected: ['Scheduled Arthroplasty Cases'],
            primaryStressDriver: 'High Mechanical Force Multi-Joint Operations',
          },
        ],
      },
    ],
    interventions: [
      {
        id: 'int-em-01',
        title: 'Mandatory Post-Night-Call Digital Pager Curfew (8 AM – 3 PM)',
        targetCohortId: 'em-dept',
        targetUnitId: 'em-night',
        targetUnitName: 'Night Resuscitation Unit',
        category: 'circadian_curfew',
        rationale: 'Post-call physicians receiving non-urgent administrative pages experience immediate REM-sleep fragmentation.',
        projectedReductionPercent: 26,
        projectedBsiReductionPercent: 26,
        actionProtocol: 'Automated 8:00 AM – 3:00 PM paging blackout with mandatory handover to daytime hospitalists.',
        status: 'recommended',
        timeToImpactDays: 21,
      },
      {
        id: 'int-surg-02',
        title: '36-Hour Shift Cap & Mandatory Circadian Micro-Sleep Pods',
        targetCohortId: 'surgery-dept',
        targetUnitId: 'surg-resident',
        targetUnitName: 'Junior Surgical Residents',
        category: 'roster_pacing',
        rationale: 'Continuous operative duty beyond 24 hours induces a 3.4x spike in chronic follicular cortisol deposition.',
        projectedReductionPercent: 32,
        projectedBsiReductionPercent: 32,
        actionProtocol: 'Split 36h calls into 14h day / 10h rest / 12h twilight rotations with dedicated quiet dark-rooms.',
        status: 'recommended',
        timeToImpactDays: 30,
      },
      {
        id: 'int-icu-03',
        title: 'Autonomic Reset Protocols Post-Code Blue Resuscitation',
        targetCohortId: 'icu-dept',
        targetUnitId: 'icu-sicu',
        targetUnitName: 'Surgical ICU (SICU)',
        category: 'workload_cap',
        rationale: 'Acute sympathetic overdrive after cardiac arrest resuscitations fails to down-regulate without structured pacing.',
        projectedReductionPercent: 18,
        projectedBsiReductionPercent: 18,
        actionProtocol: 'Mandatory 20-minute vagal stimulation / breathwork break immediately following active resuscitation.',
        status: 'recommended',
        timeToImpactDays: 14,
      },
      {
        id: 'int-card-04',
        title: 'Cath Lab On-Call Pager Roster Redundancy',
        targetCohortId: 'cardio-dept',
        targetUnitId: 'card-stemi',
        targetUnitName: 'Acute STEMI 24/7 Response Team',
        category: 'roster_pacing',
        rationale: 'Interventionalists carrying STEMI pagers 7 nights in a row develop permanent nocturnal heart rate elevation.',
        projectedReductionPercent: 22,
        projectedBsiReductionPercent: 22,
        actionProtocol: 'Limit STEMI primary on-call blocks to 3 consecutive nights with guaranteed 48h rest.',
        status: 'recommended',
        timeToImpactDays: 15,
      },
    ],
  },

  'st-jude-academy': {
    id: 'st-jude-academy',
    name: 'St. Jude International Academy & High School',
    sector: 'education',
    subdomain: 'stjude-students',
    allowedDomains: ['stjude.edu', 'stjude.org', 'k12.in', 'schools.org'],
    logoEmoji: '🎓',
    location: 'Bangalore & Hyderabad Campus',
    totalMembers: 780,
    totalSampled: 742,
    currentCycle: {
      id: 'cycle-edu-term1',
      name: 'Term 1 Pre-Board & Competitive Exam Cycle',
      period: 'Aug 1 – Sep 28, 2026',
      status: 'active',
      samplesCollected: 742,
      complianceRatePercent: 95.1,
      cliaLabCertified: true,
    },
    cohorts: [
      {
        id: 'gr-9',
        name: 'Grade 9 (Freshmen)',
        code: 'GR-09',
        iconKey: 'grade-9',
        headOfficial: 'Meera Chawla (Middle School Transition Lead)',
        averageBurnoutScore: 38,
        averageBsi: 38,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'gr9-a',
            name: 'Section 9-A',
            code: '9-A',
            iconKey: 'arts-track',
            memberCount: 38,
            sampledCount: 36,
            rawCortisolPgMg: 11.5,
            burnoutScore: 36,
            normalizedBsi: 36,
            riskLevel: 'moderate',
            previousQuarterScore: 32,
            previousQuarterBsi: 32,
            confoundersDetected: ['Pediatric Growth Rate Standard'],
            primaryStressDriver: 'High School Transition Curriculum',
          },
          {
            id: 'gr9-b',
            name: 'Section 9-B',
            code: '9-B',
            iconKey: 'stem-track',
            memberCount: 40,
            sampledCount: 38,
            rawCortisolPgMg: 12.1,
            burnoutScore: 39,
            normalizedBsi: 39,
            riskLevel: 'moderate',
            previousQuarterScore: 34,
            previousQuarterBsi: 34,
            confoundersDetected: ['Pediatric Growth Rate Standard'],
            primaryStressDriver: 'Sports & Co-Curricular Scheduling',
          },
        ],
      },
      {
        id: 'gr-10',
        name: 'Grade 10 (Foundations)',
        code: 'GR-10',
        iconKey: 'grade-10',
        headOfficial: 'Robert Hughes (Academic Dean)',
        averageBurnoutScore: 52,
        averageBsi: 52,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'gr10-a',
            name: 'Section 10-A (STEM Focus)',
            code: '10-A',
            iconKey: 'stem-track',
            memberCount: 42,
            sampledCount: 40,
            rawCortisolPgMg: 16.4,
            burnoutScore: 56,
            normalizedBsi: 56,
            riskLevel: 'moderate',
            previousQuarterScore: 48,
            previousQuarterBsi: 48,
            confoundersDetected: ['Daily Hair Wash'],
            primaryStressDriver: 'Early Foundation Tests for JEE/NEET',
          },
          {
            id: 'gr10-b',
            name: 'Section 10-B (Liberal Arts)',
            code: '10-B',
            iconKey: 'arts-track',
            memberCount: 36,
            sampledCount: 34,
            rawCortisolPgMg: 13.9,
            burnoutScore: 46,
            normalizedBsi: 46,
            riskLevel: 'moderate',
            previousQuarterScore: 44,
            previousQuarterBsi: 44,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Term Paper Submissions',
          },
        ],
      },
      {
        id: 'gr-11',
        name: 'Grade 11 (Competitive AP / JEE Cohort)',
        code: 'GR-11',
        iconKey: 'grade-11',
        headOfficial: 'Dr. K. S. Pillai (Director of Advanced Placements)',
        averageBurnoutScore: 84,
        averageBsi: 84,
        overallRisk: 'critical',
        subUnits: [
          {
            id: 'gr11-stem',
            name: 'Section 11-A (Engineering & Math)',
            code: '11-A',
            iconKey: 'stem-track',
            memberCount: 44,
            sampledCount: 43,
            rawCortisolPgMg: 26.5,
            burnoutScore: 86,
            normalizedBsi: 86,
            riskLevel: 'critical',
            previousQuarterScore: 72,
            previousQuarterBsi: 72,
            confoundersDetected: ['Late Night Screentime', 'Adolescent Melatonin Shift'],
            primaryStressDriver: 'Weekend Coaching Mocks + School Exam Pacing',
          },
          {
            id: 'gr11-med',
            name: 'Section 11-B (Biomedical & Pre-Med)',
            code: '11-B',
            iconKey: 'med-track',
            memberCount: 41,
            sampledCount: 40,
            rawCortisolPgMg: 27.9,
            burnoutScore: 89,
            normalizedBsi: 89,
            riskLevel: 'critical',
            previousQuarterScore: 74,
            previousQuarterBsi: 74,
            confoundersDetected: ['Chronic Sleep Debt (<5.5h)'],
            primaryStressDriver: 'Cumulative 14-Hour Study Days + Late Night Portals',
          },
          {
            id: 'gr11-com',
            name: 'Section 11-C (Commerce & Economics)',
            code: '11-C',
            iconKey: 'arts-track',
            memberCount: 38,
            sampledCount: 36,
            rawCortisolPgMg: 18.2,
            burnoutScore: 62,
            normalizedBsi: 62,
            riskLevel: 'elevated',
            previousQuarterScore: 55,
            previousQuarterBsi: 55,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Accountancy Practicals & Presentations',
          },
        ],
      },
      {
        id: 'gr-12',
        name: 'Grade 12 (Board Finals & College Applications)',
        code: 'GR-12',
        iconKey: 'grade-12',
        headOfficial: 'Patricia Lewis (College Counseling Lead)',
        averageBurnoutScore: 79,
        averageBsi: 79,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'gr12-stem',
            name: 'Section 12-A (Advanced STEM)',
            code: '12-A',
            iconKey: 'stem-track',
            memberCount: 45,
            sampledCount: 44,
            rawCortisolPgMg: 25.1,
            burnoutScore: 82,
            normalizedBsi: 82,
            riskLevel: 'critical',
            previousQuarterScore: 77,
            previousQuarterBsi: 77,
            confoundersDetected: ['Severe Sleep Debt'],
            primaryStressDriver: 'College Early Decision Deadlines + Pre-Board Finals',
          },
          {
            id: 'gr12-arts',
            name: 'Section 12-B (Humanities & Law)',
            code: '12-B',
            iconKey: 'arts-track',
            memberCount: 35,
            sampledCount: 33,
            rawCortisolPgMg: 21.0,
            burnoutScore: 68,
            normalizedBsi: 68,
            riskLevel: 'elevated',
            previousQuarterScore: 63,
            previousQuarterBsi: 63,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Portfolio Submissions & Entrance Mocks',
          },
        ],
      },
      {
        id: 'stem-faculty',
        name: 'STEM & Advanced Robotics Faculty',
        code: 'FAC-STEM',
        iconKey: 'stem',
        headOfficial: 'Prof. David Vance (Dean of Sciences)',
        averageBurnoutScore: 63,
        averageBsi: 63,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'stem-lab',
            name: 'Advanced Physics & Robotics Lab',
            code: 'FAC-ROB',
            iconKey: 'stem-track',
            memberCount: 18,
            sampledCount: 17,
            rawCortisolPgMg: 20.2,
            burnoutScore: 65,
            normalizedBsi: 65,
            riskLevel: 'elevated',
            previousQuarterScore: 60,
            previousQuarterBsi: 60,
            confoundersDetected: ['Night Olympiad Mentoring'],
            primaryStressDriver: 'International Olympiad Training Sessions',
          },
        ],
      },
      {
        id: 'hum-faculty',
        name: 'Humanities, Law & Economics',
        code: 'FAC-HUM',
        iconKey: 'humanities',
        headOfficial: 'Dr. Aruna Swaminathan',
        averageBurnoutScore: 47,
        averageBsi: 47,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'hum-lead',
            name: 'Debate & Model UN Faculty',
            code: 'FAC-MUN',
            iconKey: 'arts-track',
            memberCount: 16,
            sampledCount: 15,
            rawCortisolPgMg: 15.1,
            burnoutScore: 47,
            normalizedBsi: 47,
            riskLevel: 'moderate',
            previousQuarterScore: 45,
            previousQuarterBsi: 45,
            confoundersDetected: ['Weekend Travel'],
            primaryStressDriver: 'Regional Conference Coordinating',
          },
        ],
      },
      {
        id: 'ath-dept',
        name: 'Competitive Athletics Coaching Staff',
        code: 'ATH-07',
        iconKey: 'athletics',
        headOfficial: 'Coach Mark Sullivan',
        averageBurnoutScore: 55,
        averageBsi: 55,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'ath-varsity',
            name: 'Varsity Swimming & Track',
            code: 'ATH-VAR',
            iconKey: 'surge',
            memberCount: 20,
            sampledCount: 19,
            rawCortisolPgMg: 17.6,
            burnoutScore: 55,
            normalizedBsi: 55,
            riskLevel: 'moderate',
            previousQuarterScore: 53,
            previousQuarterBsi: 53,
            confoundersDetected: ['5:30 AM Pool Chlorine Leaching'],
            primaryStressDriver: 'Pre-Dawn 5:00 AM Conditioning Drills',
          },
        ],
      },
      {
        id: 'well-dept',
        name: 'Student Wellness & Mental Health Unit',
        code: 'WELL-08',
        iconKey: 'counseling',
        headOfficial: 'Dr. Neha Kapoor (Director of Counseling)',
        averageBurnoutScore: 61,
        averageBsi: 61,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'well-crisis',
            name: 'Adolescent Crisis Interventions',
            code: 'WELL-CRS',
            iconKey: 'oncall',
            memberCount: 14,
            sampledCount: 14,
            rawCortisolPgMg: 22.0,
            burnoutScore: 71,
            normalizedBsi: 71,
            riskLevel: 'elevated',
            previousQuarterScore: 66,
            previousQuarterBsi: 66,
            confoundersDetected: ['Emotional Compassion Fatigue'],
            primaryStressDriver: 'Exam Anxiety Escalations & Crisis Counseling',
          },
        ],
      },
    ],
    interventions: [
      {
        id: 'int-edu-01',
        title: 'Institutional Homework Portal Curfew (10:00 PM – 6:00 AM)',
        targetCohortId: 'gr-11',
        targetUnitId: 'gr11-med',
        targetUnitName: 'Section 11-B (Biomedical & Pre-Med)',
        category: 'circadian_curfew',
        rationale: 'Late-night digital homework submissions directly suppress adolescent slow-wave sleep and cause biological morning exhaustion.',
        projectedReductionPercent: 28,
        projectedBsiReductionPercent: 28,
        actionProtocol: 'Automatic portal upload lock between 10 PM and 6 AM. Late penalties waived for work submitted after 6 AM.',
        status: 'recommended',
        timeToImpactDays: 14,
      },
      {
        id: 'int-edu-02',
        title: '72-Hour Exam Spacing Mandate for High-Stakes Tests',
        targetCohortId: 'gr-11',
        targetUnitId: 'gr11-stem',
        targetUnitName: 'Section 11-A (Engineering & Math)',
        category: 'roster_pacing',
        rationale: 'Back-to-back testing days prevent HPA-axis down-regulation, causing continuous elevated cortisol wash.',
        projectedReductionPercent: 22,
        projectedBsiReductionPercent: 22,
        actionProtocol: 'No two major subject tests allowed within 72 hours of each other across departments.',
        status: 'recommended',
        timeToImpactDays: 20,
      },
    ],
  },

  'nexus-tech': {
    id: 'nexus-tech',
    name: 'Nexus Technologies & Stripe Global',
    sector: 'corporate',
    subdomain: 'nexus-enterprise',
    allowedDomains: ['stripe.com', 'nexustech.io', 'google.com', 'meta.com'],
    logoEmoji: '🏢',
    location: 'San Francisco & Bangalore Hubs',
    totalMembers: 680,
    totalSampled: 640,
    currentCycle: {
      id: 'cycle-corp-q3',
      name: 'Q3 Enterprise Scale & Production Delivery Cycle',
      period: 'Jul 1 – Sep 28, 2026',
      status: 'active',
      samplesCollected: 640,
      complianceRatePercent: 94.1,
      cliaLabCertified: true,
    },
    cohorts: [
      {
        id: 'infra-eng',
        name: 'Core Infrastructure & Reliability',
        code: 'ENG-INFRA',
        iconKey: 'infra',
        headOfficial: 'Elena Vance (VP of Infrastructure)',
        averageBurnoutScore: 76,
        averageBsi: 76,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'infra-oncall',
            name: 'Tier-1 Reliability On-Call Squad',
            code: 'INFRA-P1',
            iconKey: 'oncall',
            memberCount: 28,
            sampledCount: 27,
            rawCortisolPgMg: 26.1,
            burnoutScore: 84,
            normalizedBsi: 84,
            riskLevel: 'critical',
            previousQuarterScore: 74,
            previousQuarterBsi: 74,
            confoundersDetected: ['Midnight Pager Duty Sleep Fragmentation'],
            primaryStressDriver: 'Midnight Production Incidents & 5-Minute SLA Pagers',
          },
          {
            id: 'infra-cloud',
            name: 'Cloud Architecture & FinOps',
            code: 'INFRA-CLD',
            iconKey: 'day',
            memberCount: 32,
            sampledCount: 30,
            rawCortisolPgMg: 19.5,
            burnoutScore: 62,
            normalizedBsi: 62,
            riskLevel: 'elevated',
            previousQuarterScore: 60,
            previousQuarterBsi: 60,
            confoundersDetected: ['Standard Baseline'],
            primaryStressDriver: 'Cross-Timezone Datacenter Migrations',
          },
        ],
      },
      {
        id: 'ent-sales',
        name: 'Global Enterprise Sales',
        code: 'SALES-ENT',
        iconKey: 'sales',
        headOfficial: 'Marcus Sterling (Chief Revenue Officer)',
        averageBurnoutScore: 83,
        averageBsi: 83,
        overallRisk: 'critical',
        subUnits: [
          {
            id: 'sales-americas',
            name: 'Americas Enterprise Team',
            code: 'SALES-US',
            iconKey: 'sales-us',
            memberCount: 36,
            sampledCount: 35,
            rawCortisolPgMg: 28.5,
            burnoutScore: 89,
            normalizedBsi: 89,
            riskLevel: 'critical',
            previousQuarterScore: 75,
            previousQuarterBsi: 75,
            confoundersDetected: ['Red-Eye Transcontinental Flight Shifts'],
            primaryStressDriver: 'Quarter-End Quota Pressures & Cross-Country Red-Eye Flights',
          },
          {
            id: 'sales-apac',
            name: 'APAC & EMEA Expansion',
            code: 'SALES-INTL',
            iconKey: 'sales-apac',
            memberCount: 30,
            sampledCount: 28,
            rawCortisolPgMg: 24.3,
            burnoutScore: 78,
            normalizedBsi: 78,
            riskLevel: 'elevated',
            previousQuarterScore: 72,
            previousQuarterBsi: 72,
            confoundersDetected: ['Late Night US Bridge Calls'],
            primaryStressDriver: '10 PM - 2 AM HQ Alignment Video Calls',
          },
        ],
      },
      {
        id: 'sec-dept',
        name: 'Cyber Security & SecOps',
        code: 'SEC-OPS',
        iconKey: 'secops',
        headOfficial: 'David Zhang (Chief Information Security Officer)',
        averageBurnoutScore: 77,
        averageBsi: 77,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'sec-ir',
            name: 'Incident Response & Threat Hunt',
            code: 'SEC-IR',
            iconKey: 'oncall',
            memberCount: 22,
            sampledCount: 21,
            rawCortisolPgMg: 25.8,
            burnoutScore: 84,
            normalizedBsi: 84,
            riskLevel: 'critical',
            previousQuarterScore: 76,
            previousQuarterBsi: 76,
            confoundersDetected: ['Active Threat War Rooms'],
            primaryStressDriver: 'Continuous Zero-Day Vulnerability Triage',
          },
        ],
      },
      {
        id: 'ai-dept',
        name: 'Core AI & ML Engineering',
        code: 'ENG-AI',
        iconKey: 'ai',
        headOfficial: 'Dr. Maya Lin (VP of AI Research)',
        averageBurnoutScore: 70,
        averageBsi: 70,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'ai-train',
            name: 'LLM Cluster Training Squad',
            code: 'AI-TRAIN',
            iconKey: 'night',
            memberCount: 26,
            sampledCount: 25,
            rawCortisolPgMg: 22.5,
            burnoutScore: 73,
            normalizedBsi: 73,
            riskLevel: 'elevated',
            previousQuarterScore: 68,
            previousQuarterBsi: 68,
            confoundersDetected: ['Continuous Checkpoint Monitoring'],
            primaryStressDriver: 'GPU Cluster Preemption Crash Recoveries',
          },
        ],
      },
      {
        id: 'prod-ux',
        name: 'Product & User Experience',
        code: 'PROD-UX',
        iconKey: 'product',
        headOfficial: 'Sarah Lin (Chief Product Officer)',
        averageBurnoutScore: 48,
        averageBsi: 48,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'prod-core',
            name: 'Core Application Squad',
            code: 'PROD-APP',
            iconKey: 'day',
            memberCount: 34,
            sampledCount: 32,
            rawCortisolPgMg: 15.2,
            burnoutScore: 48,
            normalizedBsi: 48,
            riskLevel: 'moderate',
            previousQuarterScore: 46,
            previousQuarterBsi: 46,
            confoundersDetected: ['Regular Flexible Hours'],
            primaryStressDriver: 'Bi-Weekly Sprint Releases',
          },
        ],
      },
      {
        id: 'cs-dept',
        name: 'Customer Success & VIP Support',
        code: 'CS-OPS',
        iconKey: 'support',
        headOfficial: 'Tariq Al-Mansoor (VP of Customer Success)',
        averageBurnoutScore: 68,
        averageBsi: 68,
        overallRisk: 'elevated',
        subUnits: [
          {
            id: 'cs-esc',
            name: 'VIP Escalation Cell',
            code: 'CS-VIP',
            iconKey: 'surge',
            memberCount: 26,
            sampledCount: 25,
            rawCortisolPgMg: 23.8,
            burnoutScore: 77,
            normalizedBsi: 77,
            riskLevel: 'elevated',
            previousQuarterScore: 71,
            previousQuarterBsi: 71,
            confoundersDetected: ['High Client Churn Pressure'],
            primaryStressDriver: 'Tier-1 Client Outage Escalations',
          },
        ],
      },
      {
        id: 'fin-dept',
        name: 'Finance & Corporate Strategy',
        code: 'FIN-CORP',
        iconKey: 'finance',
        headOfficial: 'Claire Chen (CFO)',
        averageBurnoutScore: 54,
        averageBsi: 54,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'fin-close',
            name: 'Quarterly Close & Audit Squad',
            code: 'FIN-AUD',
            iconKey: 'day',
            memberCount: 20,
            sampledCount: 19,
            rawCortisolPgMg: 17.5,
            burnoutScore: 55,
            normalizedBsi: 55,
            riskLevel: 'moderate',
            previousQuarterScore: 52,
            previousQuarterBsi: 52,
            confoundersDetected: ['Standard Daytime Shifts'],
            primaryStressDriver: 'Month-End Financial Reconciliation',
          },
        ],
      },
      {
        id: 'people-dept',
        name: 'People Operations & Talent',
        code: 'HR-TALENT',
        iconKey: 'counseling',
        headOfficial: 'Jessica Barnes (Chief People Officer)',
        averageBurnoutScore: 42,
        averageBsi: 42,
        overallRisk: 'moderate',
        subUnits: [
          {
            id: 'people-ops',
            name: 'Employee Experience & Benefits',
            code: 'HR-EXP',
            iconKey: 'day',
            memberCount: 18,
            sampledCount: 17,
            rawCortisolPgMg: 12.8,
            burnoutScore: 42,
            normalizedBsi: 42,
            riskLevel: 'moderate',
            previousQuarterScore: 40,
            previousQuarterBsi: 40,
            confoundersDetected: ['Standard Daytime Shifts'],
            primaryStressDriver: 'Annual Open Enrollment Audits',
          },
        ],
      },
    ],
    interventions: [
      {
        id: 'int-corp-01',
        title: 'Asynchronous Focus Days (No-Meeting Thursdays)',
        targetCohortId: 'infra-eng',
        targetUnitId: 'infra-oncall',
        targetUnitName: 'Tier-1 Reliability On-Call Squad',
        category: 'workload_cap',
        rationale: 'Back-to-back contextual switching combined with on-call alerts induces permanent sympathetic hyper-arousal.',
        projectedReductionPercent: 24,
        projectedBsiReductionPercent: 24,
        actionProtocol: 'Total calendar lock for internal meetings every Thursday; asynchronous Slack updates only.',
        status: 'recommended',
        timeToImpactDays: 14,
      },
      {
        id: 'int-corp-02',
        title: 'Post-Quarter 72-Hour Biological Recovery Window',
        targetCohortId: 'ent-sales',
        targetUnitId: 'sales-americas',
        targetUnitName: 'Americas Enterprise Team',
        category: 'roster_pacing',
        rationale: 'The end-of-quarter push produces a 38% spike in follicular cortisol that persists for 30+ days without recovery buffers.',
        projectedReductionPercent: 30,
        projectedBsiReductionPercent: 30,
        actionProtocol: 'Mandatory 3-day quiet sprint with zero internal reviews or quota calls immediately following quarter close.',
        status: 'recommended',
        timeToImpactDays: 21,
      },
    ],
  },
};
