import { UserProfile, HairCortisolSegment, ChainOfCustody, WeeklyTelemetry, GeminiSynthesisResult } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  email: 'amithparuchuri@gmail.com',
  name: 'Amith Paruchuri',
  role: 'Medical Student / Clinical Scholar',
  sector: 'Medicine & Healthcare',
  weeklyHours: 60,
  chronotype: 'morning_lark',
  nightlySleepHours: 5.8,
  sleepQuality: 'middle_night_awakenings',
  workBoundaryBleed: 'always_on_bed',
  travelFrequency: 'occasional',
  caffeineHabit: 'immediate_waking',
  somaticSymptoms: ['brain_fog', 'tension_headaches'],
  stressDrivers: ['hospital_ward_rotations', 'clinical_exams', 'irregular_night_shifts', 'sleep_debt'],
  perceivedStressRating: 8,
  isDemo: false,
};

export const INITIAL_CHAIN_OF_CUSTODY: ChainOfCustody = {
  specimenBarcode: '#BL-8942',
  collectionSite: 'Posterior Vertex Scalp (18.5 mg)',
  sampleWeightMg: 18.5,
  currentStep: 4,
  salonPartner: 'LAKME Salon, South Extension, Delhi',
  courierTracking: 'Blue Dart Express (Air Priority - AWB #BLUEDART-DEL-9842)',
  elisaExtractionDate: 'Sep 16, 2026 • 02:00 PM IST',
};

export const CLINICAL_SURGE_SEGMENTS: HairCortisolSegment[] = [
  {
    id: 1,
    segmentKey: 'month1',
    title: 'July',
    anatomicalRegion: 'Hair Tip (2.0–3.0 cm)',
    distanceCm: '2.0–3.0 cm',
    timeWindow: '60–90 Days Ago (July)',
    cortisolPgPerMg: 11.2,
    referenceBaseline: 11.0,
    status: 'baseline',
    clinicalStatusLabel: 'Normal Healthy Baseline',
    clinicalNote: 'Stress hormone levels well within normal range (5.0–14.0 pg/mg). Good sleep patterns and steady energy.',
  },
  {
    id: 2,
    segmentKey: 'month2',
    title: 'August',
    anatomicalRegion: 'Mid-Shaft (1.0–2.0 cm)',
    distanceCm: '1.0–2.0 cm',
    timeWindow: '30–60 Days Ago (August)',
    cortisolPgPerMg: 28.4,
    referenceBaseline: 11.0,
    status: 'acute_surge',
    clinicalStatusLabel: 'Acute Stress Spike',
    clinicalNote: 'Sharp spike in stress hormone (>2.5x normal baseline). Triggered by intense workload, 23 evening calls, and cross-country travel.',
  },
  {
    id: 3,
    segmentKey: 'month3',
    title: 'September',
    anatomicalRegion: 'Scalp Root (0.0–1.0 cm)',
    distanceCm: '0.0–1.0 cm',
    timeWindow: 'Last 30 Days (September)',
    cortisolPgPerMg: 15.6,
    referenceBaseline: 11.0,
    status: 'incomplete_recovery',
    clinicalStatusLabel: 'Delayed Recovery',
    clinicalNote: 'Stress hormone remains +42% higher than baseline. Although overall meetings dropped, late-night calls continued to delay recovery.',
  },
];

export const WEEKLY_12_WEEK_TELEMETRY: WeeklyTelemetry[] = [
  // July: Baseline (Weeks 1 to 4)
  {
    weekNumber: 1,
    weekLabel: 'W1',
    month: 1,
    monthLabel: 'July',
    dateRange: 'Jun 22 - Jun 28',
    cortisolPgPerMg: 10.4,
    meetingHours: 24.5,
    eveningCalls: 1,
    flightShifts: 0,
    deepSleepHours: 1.45,
    restingHeartRate: 54,
    hrvRmssd: 68,
    isSleepDeficit: false,
    triggerDetails: 'Baseline week: Regulated circadian alignment, balanced schedule.',
  },
  {
    weekNumber: 2,
    weekLabel: 'W2',
    month: 1,
    monthLabel: 'July',
    dateRange: 'Jun 29 - Jul 05',
    cortisolPgPerMg: 11.0,
    meetingHours: 26.0,
    eveningCalls: 2,
    flightShifts: 0,
    deepSleepHours: 1.38,
    restingHeartRate: 55,
    hrvRmssd: 64,
    isSleepDeficit: false,
    triggerDetails: 'Stable cadence: Standard quarterly planning load.',
  },
  {
    weekNumber: 3,
    weekLabel: 'W3',
    month: 1,
    monthLabel: 'July',
    dateRange: 'Jul 06 - Jul 12',
    cortisolPgPerMg: 11.6,
    meetingHours: 27.5,
    eveningCalls: 2,
    flightShifts: 0,
    deepSleepHours: 1.32,
    restingHeartRate: 56,
    hrvRmssd: 62,
    isSleepDeficit: false,
    triggerDetails: 'Moderate load: Early technical design sprints.',
  },
  {
    weekNumber: 4,
    weekLabel: 'W4',
    month: 1,
    monthLabel: 'July',
    dateRange: 'Jul 13 - Jul 19',
    cortisolPgPerMg: 12.2,
    meetingHours: 29.0,
    eveningCalls: 3,
    flightShifts: 1,
    deepSleepHours: 1.18,
    restingHeartRate: 57,
    hrvRmssd: 58,
    isSleepDeficit: false,
    triggerDetails: 'Initial climb: First cross-coast travel; minor schedule friction.',
  },
  // August: Acute Surge (Weeks 5 to 8)
  {
    weekNumber: 5,
    weekLabel: 'W5',
    month: 2,
    monthLabel: 'August',
    dateRange: 'Jul 20 - Jul 26',
    cortisolPgPerMg: 18.8,
    meetingHours: 37.5,
    eveningCalls: 6,
    flightShifts: 2,
    deepSleepHours: 0.72,
    restingHeartRate: 62,
    hrvRmssd: 44,
    isSleepDeficit: true,
    triggerDetails: 'Pre-launch sprint: 6 evening calls past 8 PM breaking recovery boundaries.',
  },
  {
    weekNumber: 6,
    weekLabel: 'W6',
    month: 2,
    monthLabel: 'August',
    dateRange: 'Jul 27 - Aug 02',
    cortisolPgPerMg: 26.5,
    meetingHours: 44.0,
    eveningCalls: 9,
    flightShifts: 3,
    deepSleepHours: 0.52,
    restingHeartRate: 67,
    hrvRmssd: 28,
    isSleepDeficit: true,
    triggerDetails: 'Trigger: 44 hrs meetings + 9 late calls past 7 PM + SFO/LHR red-eye flight.',
  },
  {
    weekNumber: 7,
    weekLabel: 'W7',
    month: 2,
    monthLabel: 'August',
    dateRange: 'Aug 03 - Aug 09',
    cortisolPgPerMg: 28.4,
    meetingHours: 46.5,
    eveningCalls: 11,
    flightShifts: 4,
    deepSleepHours: 0.45,
    restingHeartRate: 69,
    hrvRmssd: 22,
    isSleepDeficit: true,
    triggerDetails: 'Peak Crisis: 46.5 hrs load, 11 late calls past 7 PM, 4 timezone hops.',
  },
  {
    weekNumber: 8,
    weekLabel: 'W8',
    month: 2,
    monthLabel: 'August',
    dateRange: 'Aug 10 - Aug 16',
    cortisolPgPerMg: 24.2,
    meetingHours: 39.0,
    eveningCalls: 7,
    flightShifts: 1,
    deepSleepHours: 0.62,
    restingHeartRate: 65,
    hrvRmssd: 31,
    isSleepDeficit: true,
    triggerDetails: 'Post-launch aftermath: High stress burden and continued evening workload.',
  },
  // September: Incomplete Recovery (Weeks 9 to 12)
  {
    weekNumber: 9,
    weekLabel: 'W9',
    month: 3,
    monthLabel: 'September',
    dateRange: 'Aug 17 - Aug 23',
    cortisolPgPerMg: 19.5,
    meetingHours: 32.0,
    eveningCalls: 5,
    flightShifts: 0,
    deepSleepHours: 0.78,
    restingHeartRate: 63,
    hrvRmssd: 38,
    isSleepDeficit: true,
    triggerDetails: 'Meetings decreased by 30%, but post-7 PM Slack & email triage continued.',
  },
  {
    weekNumber: 10,
    weekLabel: 'W10',
    month: 3,
    monthLabel: 'September',
    dateRange: 'Aug 24 - Aug 30',
    cortisolPgPerMg: 17.8,
    meetingHours: 29.5,
    eveningCalls: 4,
    flightShifts: 0,
    deepSleepHours: 0.85,
    restingHeartRate: 61,
    hrvRmssd: 43,
    isSleepDeficit: false,
    triggerDetails: 'Sub-optimal recovery: Biological reset dampened by late evening screen exposure.',
  },
  {
    weekNumber: 11,
    weekLabel: 'W11',
    month: 3,
    monthLabel: 'September',
    dateRange: 'Aug 31 - Sep 06',
    cortisolPgPerMg: 16.4,
    meetingHours: 28.0,
    eveningCalls: 4,
    flightShifts: 0,
    deepSleepHours: 0.90,
    restingHeartRate: 59,
    hrvRmssd: 48,
    isSleepDeficit: false,
    triggerDetails: 'Gradual normalization, but allostatic set-point remains elevated at +49% baseline.',
  },
  {
    weekNumber: 12,
    weekLabel: 'W12',
    month: 3,
    monthLabel: 'September',
    dateRange: 'Sep 07 - Sep 13',
    cortisolPgPerMg: 15.6,
    meetingHours: 27.5,
    eveningCalls: 3,
    flightShifts: 0,
    deepSleepHours: 0.92,
    restingHeartRate: 58,
    hrvRmssd: 51,
    isSleepDeficit: false,
    triggerDetails: 'Current Scalp Root: 15.6 pg/mg. Stress levels remain elevated due to late-night calls delaying recovery.',
  },
];

export const CLINICAL_FALLBACK_SYNTHESIS: GeminiSynthesisResult = {
  allostaticLoadScore: 78,
  allostaticCategory: 'High Stress Load',
  strainLevel: 'High',
  rootCauseCulprit: 'The workload crunch caused a sharp stress spike (28.4 pg/mg) that failed to reset because of 23 late-evening calls after 7:00 PM and 4 cross-timezone flights that repeatedly breached daily recovery boundaries.',
  hpaAxisTrajectory: 'Stress spike in Weeks 6–7 did not fully clear in Weeks 9–12 because late-night calls kept the body in an active alert state.',
  circadianDesynchronySummary: '4 cross-timezone flights combined with 23 calls after 7:00 PM disrupted regular evening wind-down boundaries, preventing full biological recovery.',
  protocols: [
    {
      id: 'circadian-reset',
      category: 'circadian',
      categoryLabel: 'Daily Sleep & Light Reset',
      title: 'Morning Light & Evening Wind-Down',
      iconType: 'sun',
      badge: 'Immediate Priority',
      description: 'Reset your natural daily energy rhythm to fall asleep faster and wake up refreshed.',
      actionItems: [
        'Wait 60–90 minutes after waking up before drinking your first coffee to let natural alertness kick in.',
        'Get 10–15 minutes of direct morning sunlight outdoors within 30 minutes of waking.',
        'Dim bright screens after 9:30 PM to let your body naturally produce sleep hormones.',
      ],
      impactMetric: 'Helps restore deep restorative sleep by 35% within 14 days.',
    },
    {
      id: 'calendar-boundary',
      category: 'calendar',
      categoryLabel: 'Google Calendar Protection',
      title: 'Protected Evening & Focus Hours',
      iconType: 'calendar',
      badge: 'Calendar Integration',
      description: 'Set automated boundaries on your Google Calendar to stop work bleeding into your evenings.',
      actionItems: [
        'Set a hard stop: decline or reschedule meeting invites after 7:00 PM local time.',
        'Add 15-minute buffers between long meetings to step away and decompress.',
        'Block Tuesday and Thursday mornings as focus time with zero meetings.',
      ],
      impactMetric: 'Stops late-night adrenaline spikes, bringing deep sleep back above 1.1 hours.',
    },
    {
      id: 'salon-audit',
      category: 'audit',
      categoryLabel: 'Follow-Up Hair Check',
      title: '8-Week Follow-Up Hair Cortisol Test',
      iconType: 'scissors',
      badge: 'Scheduled Salon Check',
      description: 'Check your progress with a quick 10-second hair snip during your next haircut.',
      actionItems: [
        'Snip fresh 1.0 cm root growth (~30 days) to confirm stress hormone returns below 12.0 pg/mg.',
        'Complimentary 10-second snip at LAKME Salon, South Extension, Delhi on Nov 14, 2026.',
        'Compare lab results against your Month 1 baseline (15.6 pg/mg) to verify full recovery.',
      ],
      impactMetric: 'Clear, lab-verified confirmation that your body has returned to balance.',
    },
  ],
  nextSalonAuditDate: 'November 14, 2026',
  confidenceScore: 96,
};
